---
# k apply -f job.yaml
# k get job.batch/node-collector-845b67c33 -n trivy-system --watch
# k describe job.batch/node-collector-845b67c33 -n trivy-system
# k events job.batch/node-collector-845b67c33 -n trivy-system
# k get pod -l job-name=node-collector-845b67c33 -n trivy-system --watch
# k get vulnerabilityreports -A -o wide
apiVersion: batch/v1
kind: Job
metadata:
  generation: 1
  labels:
    app.kubernetes.io/managed-by: trivy-operator
    node-info.collector: Trivy
    trivy-operator.resource.kind: Node
    trivy-operator.resource.name: kind-control-plane
  name: node-collector-845b67c33
  namespace: trivy-system
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 0
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    metadata:
      labels:
        app: node-collector
        batch.kubernetes.io/job-name: node-collector-845b67c33
        job-name: node-collector-845b67c33
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - k8s
        - --node
        - kind-control-plane
        command:
        - node-collector
        image: ghcr.io/aquasecurity/node-collector:0.2.1
        imagePullPolicy: IfNotPresent
        name: node-collector
        resources:
          limits:
            cpu: 500m
            memory: 500M
          requests:
            cpu: 100m
            memory: 100M
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/etcd
          name: var-lib-etcd
          readOnly: true
        - mountPath: /var/lib/kubelet
          name: var-lib-kubelet
          readOnly: true
        - mountPath: /var/lib/kube-scheduler
          name: var-lib-kube-scheduler
          readOnly: true
        - mountPath: /var/lib/kube-controller-manager
          name: var-lib-kube-controller-manager
          readOnly: true
        - mountPath: /etc/systemd
          name: etc-systemd
          readOnly: true
        - mountPath: /lib/systemd/
          name: lib-systemd
          readOnly: true
        - mountPath: /etc/kubernetes
          name: etc-kubernetes
          readOnly: true
        - mountPath: /etc/cni/net.d/
          name: etc-cni-netd
          readOnly: true
      dnsPolicy: ClusterFirst
      hostPID: true
      nodeSelector:
        kubernetes.io/hostname: kind-control-plane
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: trivy-operator
      serviceAccountName: trivy-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/etcd
          type: ""
        name: var-lib-etcd
      - hostPath:
          path: /var/lib/kubelet
          type: ""
        name: var-lib-kubelet
      - hostPath:
          path: /var/lib/kube-scheduler
          type: ""
        name: var-lib-kube-scheduler
      - hostPath:
          path: /var/lib/kube-controller-manager
          type: ""
        name: var-lib-kube-controller-manager
      - hostPath:
          path: /etc/systemd
          type: ""
        name: etc-systemd
      - hostPath:
          path: /lib/systemd
          type: ""
        name: lib-systemd
      - hostPath:
          path: /etc/kubernetes
          type: ""
        name: etc-kubernetes
      - hostPath:
          path: /etc/cni/net.d/
          type: ""
        name: etc-cni-netd
