apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-with-backup-config
spec:
  instances: 2
  storage:
    size: 1Gi
  backup:
    barmanObjectStore:
      destinationPath: "gs://devops-directive-kubernetes-course-cnpg-backups"
      googleCredentials:
        gkeEnvironment: true
    retentionPolicy: "30d"
  serviceAccountTemplate:
    metadata:
      annotations:
        iam.gke.io/gcp-service-account: cnpg-backups@kubernetes-course-424917.iam.gserviceaccount.com
#
# Barman (Backup and Recovery Manager)
# https://pgbarman.org/
# Taking an online hot backup of PostgreSQL is now as easy as ordering a good espresso coffee.
#